### PR TITLE
Output each frame separately

### PR DESCRIPTION
**Pull request by GabrielAndreiPreda**
I had an issue with transparency on the output gif, and needed the frames separately to use for a RainMeter animation anyways, so I modified the script to get them out if needed. I maintained the use as it was, the --output-frames flag is only considered if -g is set, should be backwards compatible

### CODE REVIEW

**Comment by GabrielAndreiPreda** [comment]
Oops didn't notice the formatting broke

**Comment by GabrielAndreiPreda** [comment]
I can't seem to match the format using any formatter, the important part of it is this i suppose:
```python
argparser.add_argument(
        "-of",
        "--output-frames",
        dest="output_frames",
        action="store_true",
        help=help_text["output_frames"],
    )
```

```python
# Save the image
    if not args.gif:
        glitch_img.save(full_path, compress_level=3)
        t3 = time()
        print('Glitched Image saved in "{}"'.format(full_path))
    elif not args.output_frames:
        glitch_img[0].save(
            full_path,
            format="GIF",
            append_images=glitch_img[1:],
            save_all=True,
            duration=args.duration,
            loop=args.loop,
            compress_level=3,
        )
        t3 = time()
        print(
            f'Glitched GIF saved in "{full_path}"\nFrames = {args.frames}, Duration = {args.duration}, Loop = {args.loop}'
        )
    else:
        for i, frame in enumerate(glitch_img):
            frame_path = (
                f"{full_path.rsplit('.', 1)[0]}_{i}.{full_path.rsplit('.', 1)[1]}"
            )
            frame.save(frame_path, compress_level=3)
        t3 = time()
        print(f'Glitched frames saved in "{full_path.rsplit(".", 1)[0]}_*.png"')
    print(f"Time taken to glitch: {t1 - t0}")
    print(f"Time taken to save: {t3 - t2}")
    print(f"Total Time taken: {t3 - t0}")
```
And the `test_image_to_gif_frames()` function

**Comment by TotallyNotChase** [comment]
Could you try to rebase with just the important part of the changes?

I believe I used autopep8.

**Comment by GabrielAndreiPreda** [comment]
Still a few differences in formatting unfortunately, but I put them in a separate commit

**Review by TotallyNotChase — APPROVED** [review]
LGTM

**Pull request merged**
