### PR TITLE
fixed version number being incorrect

### PR DESCRIPTION
**Pull request by MyCatCondo**
I changed `_version_` to 1.0.1

### CODE REVIEW

**Comment by TotallyNotChase** [comment]
thanks!

**Comment by MyCatCondo** [comment]
And... now I need to update. lol just got a message about it but thanks for making this script :)

**Comment by MyCatCondo** [comment]
This may need to be fixed too...
`glitch_this: Glitchify images and GIFs, with highly customizable options!`
`* Website: https://github.com/TotallyNotChase/glitch-this `
`* Version: 1.0.0`
`* Changelog: https://github.com/TotallyNotChase/glitch-this/blob/master/CHANGELOG.md`
The version number is wrong on the `glitch_this -h` text and probably the version command flag too

**Comment by TotallyNotChase** [comment]
I need to update the package on pypi to fix the versions, will do that

**Comment by TotallyNotChase** [comment]
should be fixed now

**Comment by MyCatCondo** [comment]
ok, thanks

**Pull request merged**
